SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
--
--
CREATE TABLE IF NOT EXISTS `CATEGORY` (
  `ID` smallint(3) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
--
--
CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `ID` smallint(3) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) NOT NULL,
  `STORE` varchar(100) NOT NULL,
  `LINK` text NOT NULL,
  `NUTRISCORE` varchar(1) NOT NULL,
  `CATEGORY_FK` smallint(3) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `PRODUCT_ibfk_2` FOREIGN KEY (`CATEGORY_FK`) REFERENCES `CATEGORY`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
--
--
CREATE TABLE IF NOT EXISTS `SUBSTITUTE` (
  `ID` smallint(3) NOT NULL AUTO_INCREMENT,
  `ID_PRODUCT TO SUBSTITUTE_FK` smallint(3) NOT NULL,
  `ID_PRODUCT SUBSITUTE_FK` smallint(3) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `SUBSTITUTE_ibfk_3` FOREIGN KEY (`ID_PRODUCT SUBSITUTE_FK`) REFERENCES `PRODUCT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SUBSTITUTE_ibfk_4` FOREIGN KEY (`ID_PRODUCT TO SUBSTITUTE_FK`) REFERENCES `PRODUCT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;